name: "ag1_attribution"
version: "1.0.0"

profile: "ag1_attribution"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ag1_attribution:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
